    - name: Añadir dominio nc a /etc/hosts en servidor
      ansible.builtin.lineinfile:
        path: /etc/hosts
        insertafter: "127.0.0.1 localhost"
        line: "127.0.0.1 {{ ncDomain }}"
  
  # Apache Configuration
    - name: Create document root
      file:
        path: "{{ virtualRoot }}/nc"
        state: directory
        owner: "vsftpd"
        group: "ansible"
        mode: '0755'
      tags: [ apacheNC ]

    - name: Set up Apache VirtualHost
      template:
        src: "ncApache.conf.j2"
        dest: "/etc/apache2/sites-available/{{ ncDomain }}.conf"
      tags: [ apacheNC ]

    - name: Enable new site
      shell: /usr/sbin/a2ensite {{ ncDomain }}.conf
      tags: [ apacheNC ]

    - name: Restart Apache to apply changes
      service:
        name: apache2
        state: restarted
      tags: [ apacheNC ]

  # MySQL Configuration
    - name: Creates database for Nextcloud
      mysql_db:
        name: "{{ ncDB }}"
        state: present
        login_user: root
        login_password: "{{ mysqlRootPassword }}"
      tags: [ mysql ]

    - name: Create MySQL user for Nextcloud
      mysql_user:
        name: "{{ ncDBU }}"
        password: "{{ ncDBP }}"
        priv: "{{ ncDB }}.*:ALL"
        state: present
        login_user: root
        login_password: "{{ mysqlRootPassword }}"
      tags: [ mysql ]

  # NextCloud Configuration
    - name: Download and unpack latest NextCloud
      unarchive:
        src: https://download.nextcloud.com/server/releases/latest.tar.bz2
        dest: "{{ virtualRoot }}/nc"
        remote_src: yes
        creates: "{{ virtualRoot }}/nc/nextcloud"
      tags: [ nextcloud ]

    - name: Set permissions for directories
      shell: "/usr/bin/find {{ virtualRoot }}/nc/nextcloud/ -type d -exec chmod -R 775 {} \\;"
      tags: [ nextcloud ]

    - name: Set permissions for files
      shell: "/usr/bin/find {{ virtualRoot }}/nc/nextcloud/ -type f -exec chmod 640 {} \\;"
      tags: [ nextcloud ]

  # Configuración de Nginx para WordPress
    - name: Set up Nginx-NC VirtualHost default
      template:
        src: "ncNginx.conf.j2"
        dest: "/etc/nginx/sites-available/{{ ncDomain }}"
      tags: [ nginx ]

    - name: Crear enlace simbólico para habilitar el sitio en Nginx
      file:
        src: /etc/nginx/sites-available/{{ ncDomain }}
        dest: /etc/nginx/sites-enabled/{{ ncDomain }}
        state: link
      tags: [ nginx ]

    - name: Reiniciar Nginx para aplicar cambios
      service:
        name: nginx
        state: restarted
      become: yes
      tags: [ nginx ]

  # Reiniciar MySQL para aplicar cambios
    - name: Restart MySQL to apply changes
      service:
        name: mariadb
        state: restarted
      tags: [ mysql ]
