#Virtual Root
  virtualRoot: "/var/www/web"

#MAIN.YML
  #Extra Vars
  domainName: ''
  #PhpMyAdmin Vars
  phpmyadminUser: 'admin'
  phpmyadminPass: 'admin'
    
  #MySQL Vars
  mysqlRootPassword: "mysqlrootpass"

  #Dependencies
  phpModules: [ 'php-tokenizer', 'php-curl', 'php-gd', 'php-mbstring', 'php-xmlrpc', 'php-soap', 'php-intl', 'php-zip', 'php-imagick', 'php-gmp', 'php-bcmath' ]

  #Enabled Modules
  a2modules: [ 'rewrite', 'headers', 'env', 'dir', 'mime']

# Instalation Option
  option: [ 'lamp', 'wp', 'md', '' ]
  commonNames: [ '/CN={{lampDomain}}', '/CN={{wpDomain}}', '/CN={{ncDomain}}', '/CN={{mdDomain}}' ]

#VSFTPD.YML
  #Extra Vars
  ftpUser: "ftpuser"
  ftpPass: "ftppass"

#LAMP.YML
  #Extra Vars
  lampDomain: "lampdomain.com"

#WORDPRESS.YML
  #Extra vars
  wpDomain: "wpdomain.com"
  wpDB: "wpdb"
  wpDBU: "wpdbuser"
  wpDBP: "wpdbpass"

#NEXTCLOUD.YML
  #Extra vars
  ncDomain: "nc"
  ncDB: "ncdb"
  ncDBU: "ncu"
  ncDBP: "ncu"

#MOODLE.YML
  #Extra vars
  mdDomain: "moodledomain.com"
  mdDB: "mddb"
  mdDBU: "moodledbuser"
  mdDBP: "moodledbpass"